# VehicleProfile.create([
#     { vin: "TORO_A",
#       year: 2022,
#       model: "TORO",
#       brand: "FIAT"},
#     { vin: "TORO_B",
#       year: 2022,
#       model: "TORO",
#       brand: "FIAT"},
#     { vin: "PULSE_A",
#       year: 2022,
#       model: "PULSE",
#       brand: "FIAT"},
#     { vin: "PULSE_B",
#       year: 2022,
#       model: "PULSE",
#       brand: "FIAT"},
# ])

# Gcd.create([
#     { vin: "TORO_A",
#       fuel: 36,
#       odometer: 6234,
#       created_at: "2022-09-11 19:39:45.039"},
#     { vin: "TORO_A",
#       fuel: 30,
#       odometer: 6264,
#       created_at: "2022-09-02 11:57:59.863  "},
#     { vin: "PULSE_A",
#       year: 2022,
#       model: "PULSE",
#       brand: "FIAT"},
#     { vin: "PULSE_B",
#       year: 2022,
#       model: "PULSE",
#       brand: "FIAT"},
# ])
